### ISSUE TITLE
setLoggingLevel build warning

### ISSUE THREAD

**Issue by enmiller** [klarna/klarna-mobile-sdk-spm#2]
`KlarnaMobileSDKCommon.setLoggingLevel(.error)` is showing a deprecation warning 
```
@available(*, deprecated, message: "Set logging level at per-component level instead.")
@objc public static func setLoggingLevel(_ loggingLevel: KlarnaMobileSDK.KlarnaLoggingLevel)
```

However, there are no examples of how to use this on a per-component basis either within the SDK itself or the Klarna SDK integration docs on the [website](https://docs.klarna.com/in-app/inapp-ios-overview/ios-getting-started/#common-elements-klarnalogginglevel-values).

Can the documentation be updated to show the new correct way to set the logging level of the Klarna SDK?

**Comment by NMGuner** [comment]
The documentation was updated later, sorry for not notifying here in time.
